'use client'

import { Plus, Minus } from 'lucide-react'
import { motion, AnimatePresence } from 'framer-motion'
import { useState } from 'react'

export default function FAQAccordion() {
  const [openIndex, setOpenIndex] = useState<number | null>(null)

  const faqs = [
    {
      q: 'What file types does Sappio support?',
      a: 'We support PDFs, Word documents, text files, and direct YouTube URLs. We are actively working on adding support for handwritten notes and images.'
    },
    {
      q: 'How are mind maps generated?',
      a: 'Our AI analyzes the semantic structure of your material to identify key concepts and their relationships. It then constructs a visual graph that clusters related topics, helping you visualize the "big picture" before diving into details.'
    },
    {
      q: 'Is my data private?',
      a: 'Yes. Your uploads are encrypted at rest and in transit. We do not use your personal study materials to train our public models without your explicit permission.'
    },
    {
      q: 'When do I get access?',
      a: 'We are rolling out access to waitlist members in weekly batches to ensure server stability. Join the waitlist now to lock in early bird pricing.'
    },
    {
      q: 'Can I export to Anki?',
      a: 'Absolutely. All flashcards generated by Sappio can be exported as .apkg files, which are fully compatible with Anki desktop and mobile apps.'
    }
  ]

  return (
    <div className="space-y-6">
      {faqs.map((faq, i) => {
        const isOpen = openIndex === i

        return (
          <div key={i} className="relative group">
            {/* Paper Shadow Effect */}
            <div className={`absolute inset-0 bg-[#1A1D2E] rounded-2xl transition-transform duration-300 ${isOpen ? 'translate-y-2 translate-x-2' : 'translate-y-1.5 translate-x-1.5 group-hover:translate-y-2 group-hover:translate-x-2'}`} />
            
            <div
              onClick={() => setOpenIndex(isOpen ? null : i)}
              className="relative bg-white rounded-2xl border-2 border-[#1A1D2E] cursor-pointer transition-all duration-300 overflow-hidden"
            >
              <div className="px-6 py-5 flex items-start gap-4">
                <div className={`mt-1 w-8 h-8 rounded-lg flex items-center justify-center transition-colors shrink-0 ${isOpen ? 'bg-[#5A5FF0] text-white' : 'bg-[#F8FAFB] text-[#1A1D2E]'}`}>
                  {isOpen ? <Minus className="w-4 h-4" strokeWidth={2.5} /> : <Plus className="w-4 h-4" strokeWidth={2.5} />}
                </div>

                <div className="flex-1">
                  <h3 className="text-lg font-bold text-[#1A1D2E] mb-1">
                    {faq.q}
                  </h3>

                  <AnimatePresence>
                    {isOpen && (
                      <motion.div
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: 'auto', opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        transition={{ duration: 0.2 }}
                        className="overflow-hidden"
                      >
                        <p className="pt-2 text-[#64748B] leading-relaxed font-medium">
                          {faq.a}
                        </p>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              </div>
            </div>
          </div>
        )
      })}
    </div>
  )
}
